[project]
name = "mcp-server-template"
version = "0.1.0"
description = "Yoga Class Sequencing MCP Server with Qdrant Integration"
readme = "README.md"
requires-python = ">=3.10"
authors = [{ name = "Yoga Sequencing Team" }]
keywords = ["mcp", "yoga", "sequencing", "qdrant", "wellness"]
dependencies = [
    "fastmcp",
    "qdrant-client",
    "pydantic>=2.11.7",
    "sentence-transformers>=2.2.0"
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "mypy>=1.0.0",
]
