[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "poseflow-mcp"
version = "0.1.0"
description = "soloscale_poseflow — Yoga posture MCP (HTTP streamable)"
readme = "README.md"
requires-python = ">=3.13"
authors = [{ name = "Alpic" }]
keywords = ["mcp", "llm", "alpic", "python"]


dependencies = [
  "mcp",
  "fastapi==0.115.4",
  "starlette==0.40.0",
  "uvicorn==0.30.6",
  "pydantic==2.12.0",
  "httpx==0.27.2",
  "python-dotenv==1.0.1",
  "black>=25.1.0",
]

[tool.setuptools.packages.find]
where = ["."]